Gallery/Gallery2/Controllers/HomeController.cs
using Gallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.IO;
using System.Data.SqlClient;

namespace Gallery.Controllers
{
    public class HomeController : Controller
    {
        private GalleryContext db = new GalleryContext();

        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        //GET
        public ActionResult CreateUser()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUser([Bind(Include = "Id, UserName, Email, Password")] User user)
        {
            if (ModelState.IsValid)
            {
                var enteredUser = db.Users.Where(x => x.UserName == user.UserName).FirstOrDefault();
                if (enteredUser == null)
                {
                    db.Users.Add(user);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "Sellise nimega kasutaja on juba olemas");
            }
            return View(user);
        }

        //GET
        public ActionResult LogIn()
        {
            return View();
        }


        [HttpPost]
        public ActionResult LogIn(string userName, string password)
        {
            var user = db.Users.Where(x => x.UserName == userName && x.Password == password).FirstOrDefault();
            if (user == null)
            {
                ViewBag.Error = "Sisestati vale kasjutajanimi või parool";
                return RedirectToAction("Login");
            }
            return RedirectToAction("Index");
        }
        // kuidas jääks sisselogituks kogu külastuse jooksul??

        public ActionResult FileUpload(HttpPostedFileBase file, int PictureID)
        {
            if (file != null)
            {

                // save the image path path to the database or you can send image
                // directly to database
                // in-case if you want to store byte[] ie. for DB
                using (MemoryStream ms = new MemoryStream())
                {
                    file.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                }

            }
            // after successfully uploading redirect the user
            return RedirectToAction("actionname", "controller name");
        }

        public ActionResult Index(string sortOrder)
        {
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            var pictures = db.Pictures.OrderByDescending(s => s.DateAdded).Take(3).ToList();

            //KATSETUSED:
            //var pictureId = db.Votes.Count(x => x.PictureId.Value == ).ToList();
            //int count = (from x in db.Votes where x == ... select x).Count();

            //ViewBag.DateSortParm = sortOrder == "Vote" ? "vote_Asc" : "Vote";

            //var pictures = db.Votes.GroupBy(x => x.PictureId).Select(y => new { pictureId = y.Key, Count = y.Distinct().Count() });
            //pictures = db.Votes.OrderByDescending(s => s.Votes).Take(3).ToList();

            return View(pictures);

        }


    }
}

Gallery/Gallery2/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gallery.Models;
using System.IO;

namespace Gallery.Controllers
{
    public class PictureController : Controller
    {
        private GalleryContext db = new GalleryContext();

        // GET: Picture

        // GET: Picture/Create
        public ActionResult Comment()
        {
            return View("Index");
        }
         
        // POST: Comment
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Comment([Bind(Include = "Id, PictureId, FolderId, UserId, DateAdded, CommentAdded")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("Index");
        }

        // GET: Folder/Vote
        public ActionResult Vote()
        {
            return View("Index");
        }

        // POST: Folder/Vote
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Vote([Bind(Include = "Id, UserId, FolderId, PictureId")] Vote vote)
        {
            if (ModelState.IsValid)
            {
                db.Votes.Add(vote);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("Index");
        }


        public ActionResult Index()
        {
            //Folder title = new Folder();

            //ViewBag.FolderTitle = title;

            
            return View(db.Pictures.ToList());
        }

        // GET: Picture/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // GET: Picture/Create
        public ActionResult Create()
        {
            ViewBag.FolderId = new SelectList(db.Folders, "Id", "Title");
            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName");
            return View();
        }

        // POST: Picture/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Description,DateAdded,AddedPicture,UserId,FolderId,AddedPicture")] Picture picture, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                picture.DateAdded = DateTime.Now;
                if (file != null)
                {
                    if (file.ContentType != "image/jpeg" && file.ContentType != "image/png")
                    {
                        return Content("Lisada saab ainult pildifaile");
                    }
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                        picture.AddedPicture = array;
                        db.Pictures.Add(picture);
                    }
                }
                db.SaveChanges();
                
                return RedirectToAction("Index");
            }
            ViewBag.FolderId = new SelectList(db.Folders, "Id", "Title", picture.FolderId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", picture.UserId);
            return View(picture);
        }

        public ActionResult FileUpload(HttpPostedFileBase file, int Id)
        {
            Picture picture = db.Pictures.Find(Id);
            if (picture == null)
            {
                return Content("Sellist pilti pole");
            }
            if (file != null)
            {
                if(file.ContentType != "image/jpeg" && file.ContentType != "image/png")
                {
                    return Content("Lisada saab ainult pildifaile");
                }
                using (MemoryStream ms = new MemoryStream())
                {
                    file.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                    picture.AddedPicture = array;
                    db.Entry(picture).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return Content("Unustasid faili valida");
        }

        public ActionResult Show(int id)
        {
            var picture = db.Pictures.Find(id);
            if (picture.AddedPicture == null)
            {
                return Content("Pilti pole");
            }
            return File(picture.AddedPicture, "image/jpg");
        }


        // GET: Picture/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            ViewBag.FolderId = new SelectList(db.Folders, "Id", "Title", picture.FolderId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", picture.UserId);
            return View(picture);
        }

        // POST: Picture/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,DateAdded,UserId,FolderId,AddedPicture")] Picture picture)
        {
            if (ModelState.IsValid)
            {
                Picture oldPicture = db.Pictures.Find(picture.Id);
                oldPicture.Title = picture.Title;
                oldPicture.Description = picture.Description;
                oldPicture.FolderId = picture.FolderId;
                db.Entry(oldPicture).State = EntityState.Modified;
                db.SaveChanges();


                return RedirectToAction("Index");
            }
            ViewBag.FolderId = new SelectList(db.Folders, "Id", "Title", picture.FolderId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", picture.UserId);
            return View(picture);
        }

        // GET: Picture/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // POST: Picture/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Picture picture = db.Pictures.Find(id);
            db.Pictures.Remove(picture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gallery/Gallery2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Gallery/Gallery2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Gallery/Gallery2/Views/Home/CreateUser.cshtml
@model Gallery.Models.User

@{
    ViewBag.Title = "CreateUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateUser</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gallery/Gallery2/Views/Home/Index.cshtml
@model IEnumerable<Gallery.Models.Picture>

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Gallery</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="/Home/CreateUser" class="btn btn-primary btn-lg">Register &raquo;</a></p>
</div>


<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>
<a href="/home/LogIn">Logi sisse</a>


<div class="row">
    <div class="col-md-12">
        <h2 class="text-center">Recent</h2>
    </div>
</div>

@*<div class="row">
  
       @foreach (var item in Model)
       {
        <div class="col-md-4">
            <img src='@Url.Action("Show", "Picture", new { id = item.Id })' style="width:100%;" />
        </div>
       }

 </div>*@

<div class="row">
  @foreach (var item in Model)
  {
   <div class="col-md-4">
        <a href="#" class="thumbnail" data-toggle="modal" data-target="#lightbox">
            <img src='@Url.Action("Show", "Picture", new { id = item.Id })' style="width:100%;" />
        </a>
    </div>

    <div id="lightbox" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <div class="modal-content">
                <div class="modal-body">
                    <img src="" alt="" />
                </div>
            </div>
        </div>
    </div>
  }
</div>




<div class="row">
    <div class="col-md-12">
        <h2 class="text-center">Popular</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
    <div class="col-md-3">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
    <div class="col-md-3">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
    <div class="col-md-3">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h2 class="text-center">Featured</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
    <div class="col-md-4">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
    <div class="col-md-4">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <h2 class="text-center">Albums</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
    <div class="col-md-2">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
    <div class="col-md-2">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
    <div class="col-md-2">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
    <div class="col-md-2">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>
    <div class="col-md-2">
        <img src="https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/12/2016/11/OMD51481.jpg" style="width:100%;">
    </div>    
</div>

Gallery/Gallery2/Views/Home/LogIn.cshtml
@model Gallery.Models.User

@{
    ViewBag.Title = "LogIn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LogIn</h2>

<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Log In" class="btn btn-default" />
        </div>
    </div>
</div>